version: "3.9"

services:
  backend:
    image: todo-backend
    build:
      context: ..
      dockerfile: bin/Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - backend
    working_dir: "/usr/src/app"
    restart: always

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env.db
    networks:
      - backend
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  db-express:
    image: mongo-express
    restart: always
    ports:
      - 8090:8081
    networks:
      - backend
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/

  swagger:
    image: swaggerapi/swagger-ui
    networks:
      - backend
    ports:
      - 8082:8080
    volumes:
      - ../swagger:/foo
    environment:
      - SWAGGER_JSON=/foo/swagger.yaml
    restart: always

networks:
  backend:
