import { Label, LabelKeys } from "@modules/label";

// Para no poner magical strings
const enum Keys {
  ID = "id",
  MESSAGE = "message",
  LABEL = "label",
  LABEL_ID = "labelId",
  DUE_DATE = "dueDate",
}

type Model = {
  [Keys.ID]: string; // Autogenerated
  [Keys.MESSAGE]: string;
  [Keys.LABEL]: Label;
  [Keys.DUE_DATE]: Date; // Datetime in ISO
};

export default Model;
type ID = Model[Keys.ID];

type CreationalModel = Omit<Model, Keys.DUE_DATE | Keys.ID | Keys.LABEL> & {
  [Keys.LABEL_ID]: Label[LabelKeys.ID];
  [Keys.DUE_DATE]: string;
};

type UpdateModel = Partial<CreationalModel>;

export {
  CreationalModel, ID,
  Keys,
  UpdateModel,
};
